version: '3.3'

services:
    database:
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'btcnadmin'
        MYSQL_DATABASE: 'btcncasino'
      command: --default-authentication-plugin=mysql_native_password